# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: sneider.si
email: tristan@sneider.si
description: >- # this means to ignore newlines until "baseurl:"
  Find some nifty guides, rants and information about a computer service provider.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sneider.si" # the base hostname & protocol for your site, e.g. http://example.com
author: tristan
google_analytics: UA-125019416-2

logo: /assets/logo_wide.png
image: /assets/logo_wide.png

twitter:
  username: sneider_si
  card: summary
facebook:
  publisher: Tristan.sneider
  admins: Tristan.sneider

social:
  name: Tristan Šneider
  links:
    - https://twitter.com/sneider_si
    - https://www.facebook.com/Tristan.sneider
    - https://github.com/tristaan
    - https://bitbucket.org/Tristan_
    - https://www.linkedin.com/in/tristan-%C5%A1neider-66b859158/

webmaster_verifications:
  google: 8kBL7vAyL-pacXh9wYFQbA2HlYSs2WWmtA5UyRwK_s8


date_format: "%d.%m.%Y, %a"
show_excerpts: true

# Build settings
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-menus
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - package.json
  - package-lock.json
  - webpack.config.js
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
